### ISSUE TITLE
`erlang:load_nif` fails with `Library version (2.11) not compatible (with 2.10)`

### ISSUE THREAD

**Issue by hamann** [deadtrickster/prometheus_process_collector#3]
For some reason we can't load compiled library on apline 3.4.0

``` sh
bash-4.3# mix deps.clean prometheus_process_collector
* Cleaning prometheus_process_collector
bash-4.3# mix deps.get prometheus_process_collector
Running dependency resolution
* Getting prometheus_process_collector (Hex package)
  Checking package (https://repo.hex.pm/tarballs/prometheus_process_collector-1.0.0.tar)
  Using locally cached package
bash-4.3# mix deps.compile prometheus_process_collector
===> Compiling prometheus_process_collector
make: Entering directory '/build/app/deps/prometheus_process_collector/c_src'
make: '/build/app/deps/prometheus_process_collector/c_src/../priv/prometheus_process_collector.so' is up to date.
make: Leaving directory '/build/app/deps/prometheus_process_collector/c_src'
src/prometheus_process_collector.erl:15: Warning: behaviour prometheus_collector undefined

bash-4.3# erl
Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.3.1  (abort with ^G)
1> erlang:load_nif("deps/prometheus_process_collector/priv/prometheus_process_collector",0).
{error,{bad_lib,"Library version (2.11) not compatible (with 2.10)."}}
```

Do you have any idea what could be the issue here?

**Comment by deadtrickster** [comment]
I think it's caused by glibc version mismatch, could you try to remove .so and rebuild? And what's your erlang version? 

Someone reported similar issue already: https://github.com/deadtrickster/prometheus_rabbitmq_exporter/issues/5. They solved it by updating OTP. 

Probably I should remove .so from the package...

**Comment by deadtrickster** [comment]
Ah! Your OTP version is 18... Can you update to 19?

**Comment by hamann** [comment]
At least deleting .so and rebuild doesn't help

``` sh
bash-4.3# rm deps/prometheus_process_collector/priv/prometheus_process_collector.so
bash-4.3# mix deps.compile prometheus_process_collector
===> Compiling prometheus_process_collector
make: Entering directory '/build/app/deps/prometheus_process_collector/c_src'
cc /build/app/deps/prometheus_process_collector/c_src/prometheus_process_collector_nif.o -shared -L /usr/lib/erlang/lib/erl_interface-3.8.2/lib -lerl_interface -lei -o /build/app/deps/prometheus_process_collector/c_src/../priv/prometheus_process_collector.so
make: Leaving directory '/build/app/deps/prometheus_process_collector/c_src'
bash-4.3# erl
Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.3.1  (abort with ^G)
1> erlang:load_nif("deps/prometheus_process_collector/priv/prometheus_process_collector",0).
{error,{bad_lib,"Library version (2.11) not compatible (with 2.10)."}}
```

**Comment by deadtrickster** [comment]
You need to remove object file too because NIF interface version defined via C preprocessor constant.

```
rm deps/prometheus_process_collector/c_src/prometheus_process_collector_nif.o
rm deps/prometheus_process_collector/priv/prometheus_process_collector.so
```

**Comment by deadtrickster** [comment]
Ok, I uploaded new veresion (1.0.1), without precompiled binaries. please let me know if that works for you.

**Comment by pikender** [comment]
@deadtrickster I also struggled with same issue when following setup on http://aldusleaf.org/monitoring-elixir-apps-in-2016-prometheus-and-grafana/ last night and updating to 1.0.1 seems to solve the issue.

_Please see setup and response details below_

```
➜  radar lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:    15.04
Codename:   vivid
```

From Phoenix App running on Elixir 1.3.4 and Phoenix 1.2.1

```
iex(2)> :os.type
{:unix, :linux}
```

```
prometheus-1.2.1.linux-amd64
grafana_3.1.1-1470047149_amd64.deb
```

**Visit: http://localhost:4000/metrics**

_With 1.0.0_

```
iex(2)> [info] GET /metrics
[warn] The on_load function for module prometheus_process_collector returned {:error, {:bad_lib, 'Library version (2.11) not compatible (with 2.9).'}}

[warn] The on_load function for module prometheus_process_collector returned {:error, {:bad_lib, 'Library version (2.11) not compatible (with 2.9).'}}

[error] #PID<0.12643.0> running Radar.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /metrics
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :prometheus_process_collector.collect_mf/2 is undefined (module :prometheus_process_collector is not available)
        (prometheus_process_collector) :prometheus_process_collector.collect_mf(:default, #Function<1.46898425/1 in :prometheus_text_format.registry_collect_callback/3>)
        (prometheus) /home/pikender/elixir/dev/radar/deps/prometheus/src/prometheus_collector.erl:157: :prometheus_collector.collect_mf/3
        (prometheus) /home/pikender/elixir/dev/radar/deps/prometheus/src/prometheus_registry.erl:58: :prometheus_registry."-collect/2-lc$^0/1-0-"/3
        (prometheus) /home/pikender/elixir/dev/radar/deps/prometheus/src/prometheus_registry.erl:58: :prometheus_registry.collect/2
        (prometheus) /home/pikender/elixir/dev/radar/deps/prometheus/src/formats/prometheus_text_format.erl:74: :prometheus_text_format.format/1 
        (prometheus) /home/pikender/elixir/dev/radar/deps/prometheus/src/metrics/prometheus_summary.erl:232: :prometheus_summary.observe_duration/4
        (radar) lib/app/phoenix_instrumentor.ex:18: App.PrometheusExporter.scrape_data/0
        (radar) lib/app/phoenix_instrumentor.ex:18: App.PrometheusExporter.call/2
        (radar) lib/radar/endpoint.ex:1: Radar.Endpoint.phoenix_pipeline/1
        (radar) lib/plug/debugger.ex:123: Radar.Endpoint."call (overridable 3)"/2
        (radar) lib/radar/endpoint.ex:1: Radar.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

_With 1.0.1_

```
# TYPE erlang_vm_ets_limit gauge
# HELP erlang_vm_ets_limit The maximum number of ETS tables allowed.
erlang_vm_ets_limit 2053
# TYPE erlang_vm_logical_processors gauge
# HELP erlang_vm_logical_processors The detected number of logical processors configured in the system.
erlang_vm_logical_processors 4
# TYPE erlang_vm_logical_processors_available gauge
# HELP erlang_vm_logical_processors_available The detected number of logical processors available to the Erlang runtime system.
erlang_vm_logical_processors_available 4
# TYPE erlang_vm_logical_processors_online gauge
# HELP erlang_vm_logical_processors_online The detected number of logical processors online on the system.
erlang_vm_logical_processors_online 4
# TYPE erlang_vm_port_count gauge
# HELP erlang_vm_port_count The number of ports currently existing at the local node.
erlang_vm_port_count 20
# TYPE erlang_vm_port_limit gauge
# HELP erlang_vm_port_limit The maximum number of simultaneously existing ports at the local node.
erlang_vm_port_limit 65536
# TYPE erlang_vm_process_count gauge
# HELP erlang_vm_process_count The number of processes currently existing at the local node.
erlang_vm_process_count 249
# TYPE erlang_vm_process_limit gauge
# HELP erlang_vm_process_limit The maximum number of simultaneously existing processes at the local node.
erlang_vm_process_limit 262144
# TYPE erlang_vm_schedulers gauge
# HELP erlang_vm_schedulers The number of scheduler threads used by the emulator.
erlang_vm_schedulers 4
# TYPE erlang_vm_schedulers_online gauge
# HELP erlang_vm_schedulers_online The number of schedulers online.
erlang_vm_schedulers_online 4
# TYPE erlang_vm_smp_support untyped
# HELP erlang_vm_smp_support 1 if the emulator has been compiled with SMP support, otherwise 0.
erlang_vm_smp_support 1
# TYPE erlang_vm_threads untyped
# HELP erlang_vm_threads 1 if the emulator has been compiled with thread support, otherwise 0.
erlang_vm_threads 1
# TYPE erlang_vm_thread_pool_size gauge
# HELP erlang_vm_thread_pool_size The number of async threads in the async thread pool used for asynchronous driver calls.
erlang_vm_thread_pool_size 10
# TYPE erlang_vm_time_correction untyped
# HELP erlang_vm_time_correction 1 if time correction is enabled, otherwise 0.
erlang_vm_time_correction 1
# TYPE erlang_vm_statistics_context_switches counter
# HELP erlang_vm_statistics_context_switches Total number of context switches since the system started
erlang_vm_statistics_context_switches 1082439
# TYPE erlang_vm_statistics_garbage_collection_number_of_gcs counter
# HELP erlang_vm_statistics_garbage_collection_number_of_gcs Garbage collection: number of GCs
erlang_vm_statistics_garbage_collection_number_of_gcs 151743
# TYPE erlang_vm_statistics_garbage_collection_words_reclaimed counter
# HELP erlang_vm_statistics_garbage_collection_words_reclaimed Garbage collection: words reclaimed
erlang_vm_statistics_garbage_collection_words_reclaimed 1766243595
# TYPE erlang_vm_statistics_garbage_collection_bytes_reclaimed counter
# HELP erlang_vm_statistics_garbage_collection_bytes_reclaimed Garbage collection: bytes reclaimed
erlang_vm_statistics_garbage_collection_bytes_reclaimed 14129948760
# TYPE erlang_vm_statistics_bytes_received_total counter
# HELP erlang_vm_statistics_bytes_received_total Total number of bytes received through ports
erlang_vm_statistics_bytes_received_total 63954399
# TYPE erlang_vm_statistics_bytes_output_total counter
# HELP erlang_vm_statistics_bytes_output_total Total number of bytes output to ports
erlang_vm_statistics_bytes_output_total 41182281
# TYPE erlang_vm_statistics_reductions_total counter
# HELP erlang_vm_statistics_reductions_total Total reductions
erlang_vm_statistics_reductions_total 787271236
# TYPE erlang_vm_statistics_run_queues_length_total gauge
# HELP erlang_vm_statistics_run_queues_length_total Total length of the run-queues
erlang_vm_statistics_run_queues_length_total 0
# TYPE erlang_vm_statistics_runtime_milliseconds counter
# HELP erlang_vm_statistics_runtime_milliseconds The sum of the runtime for all threads in the Erlang runtime system. Can be greater than wall clock time
erlang_vm_statistics_runtime_milliseconds 45250
# TYPE erlang_vm_statistics_wallclock_time_milliseconds counter
# HELP erlang_vm_statistics_wallclock_time_milliseconds Information about wall clock. Same as erlang_vm_statistics_runtime_milliseconds except that real time is measured
erlang_vm_statistics_wallclock_time_milliseconds 33455
# TYPE erlang_vm_memory_atom_bytes_total gauge
# HELP erlang_vm_memory_atom_bytes_total The total amount of memory currently allocated for atoms. This memory is part of the memory presented as system memory.
erlang_vm_memory_atom_bytes_total{usage="used"} 1441240
erlang_vm_memory_atom_bytes_total{usage="free"} 2713
# TYPE erlang_vm_memory_bytes_total gauge
# HELP erlang_vm_memory_bytes_total The total amount of memory currently allocated. This is the same as the sum of the memory size for processes and system.
erlang_vm_memory_bytes_total{kind="system"} 47001352
erlang_vm_memory_bytes_total{kind="processes"} 8314336
# TYPE erlang_vm_dets_tables gauge
# HELP erlang_vm_dets_tables Erlang VM DETS Tables count
erlang_vm_dets_tables 0
# TYPE erlang_vm_ets_tables gauge
# HELP erlang_vm_ets_tables Erlang VM ETS Tables count
erlang_vm_ets_tables 69
# TYPE erlang_vm_memory_processes_bytes_total gauge
# HELP erlang_vm_memory_processes_bytes_total The total amount of memory currently allocated for the Erlang processes.
erlang_vm_memory_processes_bytes_total{usage="used"} 8254776
erlang_vm_memory_processes_bytes_total{usage="free"} 59560
# TYPE erlang_vm_memory_system_bytes_total gauge
# HELP erlang_vm_memory_system_bytes_total The total amount of memory currently allocated for the emulator that is not directly related to any Erlang process. Memory presented as processes is not included in this memory.
erlang_vm_memory_system_bytes_total{usage="atom"} 1443953
erlang_vm_memory_system_bytes_total{usage="binary"} 559744
erlang_vm_memory_system_bytes_total{usage="code"} 34471952
erlang_vm_memory_system_bytes_total{usage="ets"} 2456616
erlang_vm_memory_system_bytes_total{usage="other"} 8069087
# TYPE telemetry_scrape_size_bytes summary
# HELP telemetry_scrape_size_bytes Scrape size, uncompressed
# TYPE telemetry_scrape_duration_seconds summary
# HELP telemetry_scrape_duration_seconds Scrape duration
# TYPE phoenix_controller_call_duration_microseconds histogram
# HELP phoenix_controller_call_duration_microseconds Whole controller pipeline execution time in microseconds.
# TYPE ecto_query_duration_microseconds histogram
# HELP ecto_query_duration_microseconds Total Ecto query time in microseconds.
# TYPE ecto_decode_duration_microseconds histogram
# HELP ecto_decode_duration_microseconds The time spent decoding the result in microseconds.
# TYPE http_request_duration_microseconds histogram
# HELP http_request_duration_microseconds The HTTP request latencies in microseconds.
# TYPE ecto_queue_duration_microseconds histogram
# HELP ecto_queue_duration_microseconds The time spent to check the connection out in microseconds.
# TYPE ecto_db_query_duration_microseconds histogram
# HELP ecto_db_query_duration_microseconds The time spent executing the DB query in microseconds.
# TYPE http_requests_total counter
# HELP http_requests_total Total number of HTTP requests made.
# TYPE process_open_fds gauge
# HELP process_open_fds Number of open file descriptors.
process_open_fds 28
# TYPE process_max_fds gauge
# HELP process_max_fds Maximum number of open file descriptors.
process_max_fds 1024
# TYPE process_start_time_seconds gauge
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
process_start_time_seconds 1476950909
# TYPE process_uptime_seconds gauge
# HELP process_uptime_seconds Process uptime in seconds.
process_uptime_seconds 32
# TYPE process_threads_total gauge
# HELP process_threads_total Process Threads count.
process_threads_total 19
# TYPE process_virtual_memory_bytes gauge
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
process_virtual_memory_bytes 1172119552
# TYPE process_resident_memory_bytes gauge
# HELP process_resident_memory_bytes Resident memory size in bytes.
process_resident_memory_bytes 90710016
# TYPE process_cpu_seconds_total counter
# HELP process_cpu_seconds_total Process CPU seconds total.
process_cpu_seconds_total{kind="utime"} 45.26
process_cpu_seconds_total{kind="stime"} 4.12
```

**Comment by deadtrickster** [comment]
@pikender Sorry to hear that, and glad the problem resolved. You can find me on (elixir-lang) Slack (I'm deadtrickster here too). Also I have #prometheus channel on Slack now too. I also use IRC (#elixir-lang, #erlang on Freenode).

**Comment by pikender** [comment]
@deadtrickster sure. 

I was not sure whether its a mistake in my setup so waited a bit to cross-confirm before bothering you.

I was checking the available versions and saw one published just now :), tried and worked.

I came back to other [issue](https://github.com/deadtrickster/prometheus_process_collector/issues/2) mentioning the issue and solution but saw this one which you already tackled.

Hats off to you for fixing almost in no time :+1: :heart:

**Comment by hamann** [comment]
@deadtrickster It's working for me as well with 1.0.1, even with otp 18. Thanks a lot!
